# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(default='6d40f2b665e34ba7b417b746863a9bf9', max_length=32, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('short_description', models.CharField(max_length=255)),
            ],
        ),
    ]
