# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.CharField(default='ec20410bddc348ac8ddba44a4d9fd171', max_length=32, primary_key=True, serialize=False),
        ),
    ]
