# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 00:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20180302_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.CharField(default='8195ebccad6d40a1b02bb67835345d74', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 3, 0, 22, 11, 837028)),
        ),
    ]
