# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20180303_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.CharField(default='96ee876b5c9445b694c036041d588438', max_length=32, primary_key=True, serialize=False),
        ),
    ]
