# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20180303_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.CharField(default='2f85abb372be43809873db22c05125df', max_length=32, primary_key=True, serialize=False),
        ),
    ]
