# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20180303_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.CharField(default='f9bacbd2a8674890a6fd950f69c19aa9', max_length=32, primary_key=True, serialize=False),
        ),
    ]
