# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20180303_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.CharField(default='e2ef0cf2764346a28c4817a9ccf59ab4', max_length=32, primary_key=True, serialize=False),
        ),
    ]
